version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 1048576 # 1MB
        backupCount: 3
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 1048576 # 1MB
        backupCount: 3
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 1048576 # 1MB
        backupCount: 3
        encoding: utf8

#loggers:
#    combiner:
#        level: DEBUG
#        handlers: [debug_file_handler]
#    info:
#        level: INFO
#        handlers: [info_file_handler]
#    error:
#        level: ERROR
#        handlers: [error_file_handler]

root:
    levels: INFO, DEBUG, ERROR
    handlers: [info_file_handler, debug_file_handler, error_file_handler]
#    propagate: True